version: "2"
volumes:
  resin-data:
services:
  homebridge:
    image: oznu/homebridge:latest
    network_mode: host
    environment:
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8080
      - TERMINATE_ON_ERROR=1
    privileged: true
    restart: always
    volumes:
      - "resin-data:/homebridge"
    labels:
      io.balena.features.kernel-modules: "1"
  mosquitto:
    image: eclipse-mosquitto:latest
    network_mode: host
    restart: always
